config/routes.rb
Rails.application.routes.draw do
  resources :card_pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord; end

app/models/card_page.rb
class CardPage < ApplicationRecord
  attr_accessor :cards_list

  def cards_list
    cards.split('-').map(&:to_i)
  end

  def cards_list=(arr)
    send('cards=', arr.join('-'))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/card_pages_controller.rb
class CardPagesController < ApplicationController
  before_action :set_card_page, only: [:show, :edit, :update, :destroy]

  # GET /card_pages
  # GET /card_pages.json
  def index
    @card_pages = CardPage.all
  end

  # GET /card_pages/1
  # GET /card_pages/1.json
  def show
  end

  # GET /card_pages/new
  def new
    @card_page = CardPage.new
  end

  # GET /card_pages/1/edit
  def edit
  end

  # POST /card_pages
  # POST /card_pages.json
  def create
    @card_page = CardPage.new(card_page_params)

    respond_to do |format|
      if @card_page.save
        format.html { redirect_to @card_page, notice: 'Card page was successfully created.' }
        format.json { render :show, status: :created, location: @card_page }
      else
        format.html { render :new }
        format.json { render json: @card_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_pages/1
  # PATCH/PUT /card_pages/1.json
  def update
    respond_to do |format|
      if @card_page.update(card_page_params)
        format.html { redirect_to @card_page, notice: 'Card page was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_page }
      else
        format.html { render :edit }
        format.json { render json: @card_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_pages/1
  # DELETE /card_pages/1.json
  def destroy
    @card_page.destroy
    respond_to do |format|
      format.html { redirect_to card_pages_url, notice: 'Card page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_page
      @card_page = CardPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_page_params
      params.require(:card_page).permit(:title, :h1, :body, :cards)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_pages_helper.rb
module CardPagesHelper
end

app/views/card_pages/_form.html.erb
<%= form_with(model: card_page, local: true) do |form| %>
  <% if card_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card_page.errors.count, "error") %> prohibited this card_page from being saved:</h2>

      <ul>
      <% card_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :h1 %>
    <%= form.text_field :h1 %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :cards %>
    <%= form.text_field :cards %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/card_pages/edit.html.erb
<h1>Editing Card Page</h1>

<%= render 'form', card_page: @card_page %>

<%= link_to 'Show', @card_page %> |
<%= link_to 'Back', card_pages_path %>

app/views/card_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Card Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>H1</th>
      <th>Body</th>
      <th>Cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @card_pages.each do |card_page| %>
      <tr>
        <td><%= card_page.title %></td>
        <td><%= card_page.h1 %></td>
        <td><%= card_page.body %></td>
        <td><%= card_page.cards %></td>
        <td><%= link_to 'Show', card_page %></td>
        <td><%= link_to 'Edit', edit_card_page_path(card_page) %></td>
        <td><%= link_to 'Destroy', card_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card Page', new_card_page_path %>

app/views/card_pages/new.html.erb
<h1>New Card Page</h1>

<%= render 'form', card_page: @card_page %>

<%= link_to 'Back', card_pages_path %>

app/views/card_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card_page.title %>
</p>

<p>
  <strong>H1:</strong>
  <%= @card_page.h1 %>
</p>

<p>
  <strong>Body:</strong>
  <%= @card_page.body %>
</p>

<p>
  <strong>Cards:</strong>
  <%= @card_page.cards %>
</p>

<%= link_to 'Edit', edit_card_page_path(@card_page) %> |
<%= link_to 'Back', card_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MpTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>